version: '3.1'

services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: maddytec
    ports:
      - "27017:27017"
    volumes:
      - ./data/db
    networks:
      - mongo-compose-network
    restart: always

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: maddytec
      ME_CONFIG_MONGODB_URL: mongodb://root:maddytec@mongo:27017/
    depends_on:
      - mongo
    networks:
      - mongo-compose-network
    restart: always

networks:
  mongo-compose-network:
    driver: bridge